# MLflow + Hyperopt — Training & Tracking an ANN Model
Channel: Asadullah AI

Prerequisite: Basic understanding of Machine Learning and Artificial Neural Networks (ANN).

### What you will learn

- Build a Keras Sequential ANN for Wine Quality prediction
- Apply normalization using mean & variance
- Run Hyperopt for hyperparameter search (learning rate, momentum)
- Track every experiment in MLflow (nested runs)
- Register the best model in the Model Registry
- Load and inference using PyFunc

In [13]:
import keras
import numpy as np
import pandas as pd
from hyperopt import STATUS_OK,Trials,fmin,hp,tpe
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

import mlflow
from mlflow.models import infer_signature

In [29]:
mlflow.set_tracking_uri(uri="http://127.0.0.1:5000/")

In [30]:
## load the dataset
data=pd.read_csv(
    "https://raw.githubusercontent.com/mlflow/mlflow/master/tests/datasets/winequality-white.csv",
    sep=";",
)
data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

In [31]:
## Split the data into training,validation and test sets

train,test=train_test_split(data,test_size=0.25,random_state=42)
train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
2835,6.3,0.25,0.22,3.30,0.048,41.0,161.0,0.99256,3.16,0.50,10.5,6
1157,7.8,0.30,0.29,16.85,0.054,23.0,135.0,0.99980,3.16,0.38,9.0,6
744,7.4,0.38,0.27,7.50,0.041,24.0,160.0,0.99535,3.17,0.43,10.0,5
1448,7.4,0.16,0.49,1.20,0.055,18.0,150.0,0.99170,3.23,0.47,11.2,6
3338,7.2,0.27,0.28,15.20,0.046,6.0,41.0,0.99665,3.17,0.39,10.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4426,6.2,0.21,0.52,6.50,0.047,28.0,123.0,0.99418,3.22,0.49,9.9,6
466,7.0,0.14,0.32,9.00,0.039,54.0,141.0,0.99560,3.22,0.43,9.4,6
3092,7.6,0.27,0.52,3.20,0.043,28.0,152.0,0.99129,3.02,0.53,11.4,6
3772,6.3,0.24,0.29,13.70,0.035,53.0,134.0,0.99567,3.17,0.38,10.6,6
860,8.1,0.27,0.35,1.70,0.030,38.0,103.0,0.99255,3.22,0.63,10.4,8

In [32]:
train[['quality']].values.ravel()

array([6, 6, 5, ..., 6, 6, 8], shape=(3673,))

In [33]:
train_x=train.drop(['quality'],axis=1).values
train_y=train[['quality']].values.ravel()

## test dataset
test_x=test.drop(['quality'],axis=1).values
test_y=test[['quality']].values.ravel()

## splitting this train data into train and validation

train_x,valid_x,train_y,valid_y=train_test_split(train_x,train_y,test_size=0.20,random_state=42)

signature=infer_signature(train_x,train_y)

In [34]:
np.mean(train_x,axis=0)

array([6.86621852e+00, 2.80377808e-01, 3.32597005e-01, 6.42164738e+00,
       4.55513955e-02, 3.53556841e+01, 1.38792376e+02, 9.94074221e-01,
       3.18919333e+00, 4.88396869e-01, 1.05005673e+01])

In [35]:
train_x.shape[1]

11

In [36]:
### ANN Model

def train_model(params,epochs,train_x,train_y,valid_x,valid_y,test_x,test_y):

    ## Define model architecture
    mean=np.mean(train_x,axis=0)
    var=np.var(train_x,axis=0)

    model=keras.Sequential(
        [
            keras.Input([train_x.shape[1]]),
            keras.layers.Normalization(mean=mean,variance=var),
            keras.layers.Dense(64,activation='relu'),
            keras.layers.Dense(1)

        ]
    )

    ## compile the model
    model.compile(
        optimizer=keras.optimizers.SGD(
        learning_rate=params["lr"],
        momentum=params["momentum"]
    ),
    loss="mean_squared_error",
    metrics=[keras.metrics.RootMeanSquaredError()]
    )

    ## Train the ANN model with lr and momentum params wwith MLFLOW tracking
    with mlflow.start_run(nested=True):
        model.fit(train_x,train_y,validation_data=(valid_x,valid_y),
                  epochs=epochs,
                  batch_size=64)
        
        ## Evaluate the model
        eval_result=model.evaluate(valid_x,valid_y,batch_size=64)

        eval_rmse=eval_result[1]

        ## Log the parameters and results
        mlflow.log_params(params)
        mlflow.log_metric("eval_rmse",eval_rmse)

        ## log the model

        mlflow.tensorflow.log_model(model,"ann-model",signature=signature)

        return {"loss": eval_rmse, "status": STATUS_OK, "model": model}

In [37]:
def objective(params):
    # MLflow will track the parameters and results for each run
    result = train_model(
        params,
        epochs=3,
        train_x=train_x,
        train_y=train_y,
        valid_x=valid_x,
        valid_y=valid_y,
        test_x=test_x,
        test_y=test_y,
    )
    return result

In [38]:
space={
    "lr":hp.loguniform("lr",np.log(1e-5),np.log(1e-1)),
    "momentum":hp.uniform("momentum",0.0,1.0)

}

In [39]:
mlflow.set_experiment("wine-quality")
with mlflow.start_run():
    # Conduct the hyperparameter search using Hyperopt
    trials=Trials()
    best=fmin( 
        fn=objective,
        space=space,
        algo=tpe.suggest, # Tree-structured parzen estimator 
        max_evals=4,
        trials=trials
    )

    # Fetch the details of the best run
    best_run = sorted(trials.results, key=lambda x: x["loss"])[0]

    # Log the best parameters, loss, and model
    mlflow.log_params(best)
    mlflow.log_metric("eval_rmse", best_run["loss"])
    mlflow.tensorflow.log_model(best_run["model"], "ann-best-model", signature=signature)

    # Print out the best parameters and corresponding loss
    print(f"Best parameters: {best}")
    print(f"Best eval rmse: {best_run['loss']}")

2026/09/07 04:12:39 INFO mlflow.tracking.fluent: Experiment with name 'wine-quality' does not exist. Creating a new experiment.

Epoch 1/3

 1/46 ━━━━━━━━━━━━━━━━━━━━ 6:25 9s/step - loss: 44.0197 - root_mean_squared_error: 6.6347
 2/46 ━━━━━━━━━━━━━━━━━━━━ 2s 62ms/step - loss: 37.0522 - root_mean_squared_error: 6.0598
 3/46 ━━━━━━━━━━━━━━━━━━━━ 3s 81ms/step - loss: 31.9887 - root_mean_squared_error: 5.5984
 4/46 ━━━━━━━━━━━━━━━━━━━━ 3s 76ms/step - loss: 28.2201 - root_mean_squared_error: 5.2270
 5/46 ━━━━━━━━━━━━━━━━━━━━ 2s 72ms/step - loss: 25.3676 - root_mean_squared_error: 4.9288
 6/46 ━━━━━━━━━━━━━━━━━━━━ 2s 67ms/step - loss: 23.1850 - root_mean_squared_error: 4.6912
 7/46 ━━━━━━━━━━━━━━━━━━━━ 3s 78ms/step - loss: 21.4143 - root_mean_squared_error: 4.4903
 8/46 ━━━━━━━━━━━━━━━━━━━━ 2s 78ms/step - loss: 19.9397 - root_mean_squared_error: 4.3166
 9/46 ━━━━━━━━━━━━━━━━━━━━ 2s 75ms/step - loss: 18.6976 - root_mean_squared_error: 4.1659
10/46 ━━━━━━━━━━━━━━━━━━━━ 2s 77ms/step - loss: 17.6325 - root_mean_squared_error: 4.0330
11/46 ━━━━━━━━━━━━━━━━━━━━ 2s 79ms/step - loss: 16.7106 - root_mean_squared_error: 3.9152
12/46 ━━━━━━━━━━━━━━━━━━━━ 2s 76ms/step - loss: 15.9041 - root_mean_squared_error: 3.8099
13/46 ━━━━━━━━━━━━━━━━━━━━ 2s 76ms/step - loss: 15.1899 - root_mean_squared_error: 3.7147
14/46 ━━━━━━━━━━━━━━━━━━━━ 2s 75ms/step - loss: 14.5512 - root_mean_squared_error: 3.6279
16/46 ━━━━━━━━━━━━━━━━━━━━ 2s 68ms/step - loss: 13.4757 - root_mean_squared_error: 3.4793
17/46 ━━━━━━━━━━━━━━━━━━━━ 2s 70ms/step - loss: 13.0099 - root_mean_squared_error: 3.4133
18/46 ━━━━━━━━━━━━━━━━━━━━ 1s 69ms/step - loss: 12.5836 - root_mean_squared_error: 3.3520
19/46 ━━━━━━━━━━━━━━━━━━━━ 1s 68ms/step - loss: 12.1910 - root_mean_squared_error: 3.2947
20/46 ━━━━━━━━━━━━━━━━━━━━ 1s 68ms/step - loss: 11.8274 - root_mean_squared_error: 3.2409
21/46 ━━━━━━━━━━━━━━━━━━━━ 1s 68ms/step - loss: 11.4896 - root_mean_squared_error: 3.1901
22/46 ━━━━━━━━━━━━━━━━━━━━ 1s 69ms/step - loss: 11.1753 - root_mean_squared_error: 3.1424
23/46 ━━━━━━━━━━━━━━━━━━━━ 1s 68ms/step - loss: 10.8824 - root_mean_squared_error: 3.0973
24/46 ━━━━━━━━━━━━━━━━━━━━ 1s 69ms/step - loss: 10.6084 - root_mean_squared_error: 3.0548
25/46 ━━━━━━━━━━━━━━━━━━━━ 1s 70ms/step - loss: 10.3512 - root_mean_squared_error: 3.0143
26/46 ━━━━━━━━━━━━━━━━━━━━ 1s 70ms/step - loss: 10.1091 - root_mean_squared_error: 2.9758
28/46 ━━━━━━━━━━━━━━━━━━━━ 1s 67ms/step - loss: 9.6660 - root_mean_squared_error: 2.9044
29/46 ━━━━━━━━━━━━━━━━━━━━ 1s 67ms/step - loss: 9.4623 - root_mean_squared_error: 2.8711
30/46 ━━━━━━━━━━━━━━━━━━━━ 1s 69ms/step - loss: 9.2692 - root_mean_squared_error: 2.8393
31/46 ━━━━━━━━━━━━━━━━━━━━ 1s 69ms/step - loss: 9.0856 - root_mean_squared_error: 2.8087
32/46 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 8.9108 - root_mean_squared_error: 2.7793
33/46 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 8.7442 - root_mean_squared_error: 2.7511
34/46 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 8.5856 - root_mean_squared_error: 2.7240
35/46 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 8.4340 - root_mean_squared_error: 2.6979
36/46 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 8.2889 - root_mean_squared_error: 2.6728
37/46 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 8.1500 - root_mean_squared_error: 2.6485
39/46 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 7.8891 - root_mean_squared_error: 2.6024
41/46 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 7.6486 - root_mean_squared_error: 2.5594
42/46 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 7.5351 - root_mean_squared_error: 2.5389
43/46 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 7.4257 - root_mean_squared_error: 2.5189
44/46 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 7.3205 - root_mean_squared_error: 2.4997
45/46 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 7.2191 - root_mean_squared_error: 2.4811
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 7.1213 - root_mean_squared_error: 2.4630
46/46 ━━━━━━━━━━━━━━━━━━━━ 15s 144ms/step - loss: 2.7218 - root_mean_squared_error: 1.6498 - val_loss: 0.9489 - val_root_mean_squared_error: 0.9741

Epoch 2/3

 1/46 ━━━━━━━━━━━━━━━━━━━━ 16s 369ms/step - loss: 1.0138 - root_mean_squared_error: 1.0069
 2/46 ━━━━━━━━━━━━━━━━━━━━ 2s 61ms/step - loss: 0.9797 - root_mean_squared_error: 0.9896
 4/46 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - loss: 0.9030 - root_mean_squared_error: 0.9492
 6/46 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.8874 - root_mean_squared_error: 0.9412
 7/46 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - loss: 0.8801 - root_mean_squared_error: 0.9374
 8/46 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - loss: 0.8764 - root_mean_squared_error: 0.9355
 9/46 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step - loss: 0.8711 - root_mean_squared_error: 0.9327
10/46 ━━━━━━━━━━━━━━━━━━━━ 2s 59ms/step - loss: 0.8653 - root_mean_squared_error: 0.9296
11/46 ━━━━━━━━━━━━━━━━━━━━ 2s 70ms/step - loss: 0.8584 - root_mean_squared_error: 0.9259
12/46 ━━━━━━━━━━━━━━━━━━━━ 2s 86ms/step - loss: 0.8529 - root_mean_squared_error: 0.9229
13/46 ━━━━━━━━━━━━━━━━━━━━ 2s 86ms/step - loss: 0.8478 - root_mean_squared_error: 0.9201
14/46 ━━━━━━━━━━━━━━━━━━━━ 2s 85ms/step - loss: 0.8424 - root_mean_squared_error: 0.9172
15/46 ━━━━━━━━━━━━━━━━━━━━ 3s 97ms/step - loss: 0.8384 - root_mean_squared_error: 0.9150
16/46 ━━━━━━━━━━━━━━━━━━━━ 2s 96ms/step - loss: 0.8337 - root_mean_squared_error: 0.9124
17/46 ━━━━━━━━━━━━━━━━━━━━ 2s 95ms/step - loss: 0.8301 - root_mean_squared_error: 0.9104
19/46 ━━━━━━━━━━━━━━━━━━━━ 2s 88ms/step - loss: 0.8246 - root_mean_squared_error: 0.9074
20/46 ━━━━━━━━━━━━━━━━━━━━ 2s 89ms/step - loss: 0.8219 - root_mean_squared_error: 0.9060
22/46 ━━━━━━━━━━━━━━━━━━━━ 2s 85ms/step - loss: 0.8163 - root_mean_squared_error: 0.9029
23/46 ━━━━━━━━━━━━━━━━━━━━ 2s 92ms/step - loss: 0.8138 - root_mean_squared_error: 0.9015
24/46 ━━━━━━━━━━━━━━━━━━━━ 2s 97ms/step - loss: 0.8117 - root_mean_squared_error: 0.9003
25/46 ━━━━━━━━━━━━━━━━━━━━ 2s 97ms/step - loss: 0.8097 - root_mean_squared_error: 0.8992
26/46 ━━━━━━━━━━━━━━━━━━━━ 2s 102ms/step - loss: 0.8076 - root_mean_squared_error: 0.8981
27/46 ━━━━━━━━━━━━━━━━━━━━ 2s 110ms/step - loss: 0.8058 - root_mean_squared_error: 0.8971
28/46 ━━━━━━━━━━━━━━━━━━━━ 2s 116ms/step - loss: 0.8038 - root_mean_squared_error: 0.8959
29/46 ━━━━━━━━━━━━━━━━━━━━ 2s 134ms/step - loss: 0.8023 - root_mean_squared_error: 0.8951
30/46 ━━━━━━━━━━━━━━━━━━━━ 2s 135ms/step - loss: 0.8008 - root_mean_squared_error: 0.8943
31/46 ━━━━━━━━━━━━━━━━━━━━ 2s 134ms/step - loss: 0.7995 - root_mean_squared_error: 0.8936
32/46 ━━━━━━━━━━━━━━━━━━━━ 1s 133ms/step - loss: 0.7982 - root_mean_squared_error: 0.8929
33/46 ━━━━━━━━━━━━━━━━━━━━ 1s 137ms/step - loss: 0.7969 - root_mean_squared_error: 0.8921
34/46 ━━━━━━━━━━━━━━━━━━━━ 1s 137ms/step - loss: 0.7955 - root_mean_squared_error: 0.8914
35/46 ━━━━━━━━━━━━━━━━━━━━ 1s 137ms/step - loss: 0.7942 - root_mean_squared_error: 0.8906
36/46 ━━━━━━━━━━━━━━━━━━━━ 1s 136ms/step - loss: 0.7929 - root_mean_squared_error: 0.8899
37/46 ━━━━━━━━━━━━━━━━━━━━ 1s 135ms/step - loss: 0.7916 - root_mean_squared_error: 0.8892
38/46 ━━━━━━━━━━━━━━━━━━━━ 1s 136ms/step - loss: 0.7901 - root_mean_squared_error: 0.8883
39/46 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - loss: 0.7887 - root_mean_squared_error: 0.8875
40/46 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - loss: 0.7873 - root_mean_squared_error: 0.8868
41/46 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - loss: 0.7860 - root_mean_squared_error: 0.8860
42/46 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - loss: 0.7846 - root_mean_squared_error: 0.8852
43/46 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - loss: 0.7833 - root_mean_squared_error: 0.8845
44/46 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - loss: 0.7819 - root_mean_squared_error: 0.8837
45/46 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - loss: 0.7805 - root_mean_squared_error: 0.8829
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - loss: 0.7791 - root_mean_squared_error: 0.8821
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 178ms/step - loss: 0.7146 - root_mean_squared_error: 0.8453 - val_loss: 0.6051 - val_root_mean_squared_error: 0.7779

Epoch 3/3

 1/46 ━━━━━━━━━━━━━━━━━━━━ 11s 246ms/step - loss: 0.4484 - root_mean_squared_error: 0.6696
 5/46 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.5061 - root_mean_squared_error: 0.7110
 7/46 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.5238 - root_mean_squared_error: 0.7232
 8/46 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.5361 - root_mean_squared_error: 0.7314
 9/46 ━━━━━━━━━━━━━━━━━━━━ 2s 56ms/step - loss: 0.5470 - root_mean_squared_error: 0.7386
10/46 ━━━━━━━━━━━━━━━━━━━━ 2s 68ms/step - loss: 0.5607 - root_mean_squared_error: 0.7475
12/46 ━━━━━━━━━━━━━━━━━━━━ 2s 61ms/step - loss: 0.5820 - root_mean_squared_error: 0.7612
17/46 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step - loss: 0.6099 - root_mean_squared_error: 0.7793
21/46 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.6202 - root_mean_squared_error: 0.7860
24/46 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.6230 - root_mean_squared_error: 0.7880
28/46 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.6249 - root_mean_squared_error: 0.7893
35/46 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.6255 - root_mean_squared_error: 0.7900
44/46 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.6215 - root_mean_squared_error: 0.7876
46/46 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.5941 - root_mean_squared_error: 0.7708 - val_loss: 0.5547 - val_root_mean_squared_error: 0.7448

 1/12 ━━━━━━━━━━━━━━━━━━━━ 5s 455ms/step - loss: 0.4453 - root_mean_squared_error: 0.6673
 2/12 ━━━━━━━━━━━━━━━━━━━━ 2s 255ms/step - loss: 0.4327 - root_mean_squared_error: 0.6577
 3/12 ━━━━━━━━━━━━━━━━━━━━ 2s 278ms/step - loss: 0.4593 - root_mean_squared_error: 0.6771
 4/12 ━━━━━━━━━━━━━━━━━━━━ 2s 257ms/step - loss: 0.4692 - root_mean_squared_error: 0.6844
 5/12 ━━━━━━━━━━━━━━━━━━━━ 1s 244ms/step - loss: 0.4759 - root_mean_squared_error: 0.6893
 6/12 ━━━━━━━━━━━━━━━━━━━━ 1s 251ms/step - loss: 0.4809 - root_mean_squared_error: 0.6930
 7/12 ━━━━━━━━━━━━━━━━━━━━ 1s 255ms/step - loss: 0.4875 - root_mean_squared_error: 0.6977
 8/12 ━━━━━━━━━━━━━━━━━━━━ 0s 241ms/step - loss: 0.4957 - root_mean_squared_error: 0.7034
 9/12 ━━━━━━━━━━━━━━━━━━━━ 0s 250ms/step - loss: 0.5028 - root_mean_squared_error: 0.7084
10/12 ━━━━━━━━━━━━━━━━━━━━ 0s 230ms/step - loss: 0.5086 - root_mean_squared_error: 0.7125
11/12 ━━━━━━━━━━━━━━━━━━━━ 0s 228ms/step - loss: 0.5127 - root_mean_squared_error: 0.7154
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 243ms/step - loss: 0.5162 - root_mean_squared_error: 0.7178
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 276ms/step - loss: 0.5547 - root_mean_squared_error: 0.7448

  0%|          | 0/4 [00:32<?, ?trial/s, best loss=?]

2026/09/07 04:13:14 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run honorable-whale-535 at: http://127.0.0.1:5000/#/experiments/1/runs/dbe8fe3494b3403f92e6d39184fd91a1

🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

Epoch 1/3

 1/46 ━━━━━━━━━━━━━━━━━━━━ 2:53 4s/step - loss: 38.2399 - root_mean_squared_error: 6.1838
 9/46 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 28.1599 - root_mean_squared_error: 5.2701
11/46 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 26.0099 - root_mean_squared_error: 5.0466
14/46 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 23.4677 - root_mean_squared_error: 4.7710
16/46 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 22.1074 - root_mean_squared_error: 4.6180
17/46 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 21.5004 - root_mean_squared_error: 4.5483
19/46 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 20.3926 - root_mean_squared_error: 4.4183
20/46 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 19.8851 - root_mean_squared_error: 4.3574
23/46 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 18.5292 - root_mean_squared_error: 4.1908
25/46 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 17.7418 - root_mean_squared_error: 4.0913
29/46 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 16.3970 - root_mean_squared_error: 3.9169
30/46 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 16.1000 - root_mean_squared_error: 3.8775
32/46 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 15.5433 - root_mean_squared_error: 3.8028
33/46 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 15.2823 - root_mean_squared_error: 3.7673
34/46 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 15.0315 - root_mean_squared_error: 3.7330
36/46 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 14.5588 - root_mean_squared_error: 3.6675
37/46 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 14.3361 - root_mean_squared_error: 3.6363
38/46 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 14.1223 - root_mean_squared_error: 3.6062
40/46 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 13.7175 - root_mean_squared_error: 3.5486
41/46 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 13.5259 - root_mean_squared_error: 3.5211
42/46 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 13.3407 - root_mean_squared_error: 3.4944
43/46 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 13.1617 - root_mean_squared_error: 3.4684
44/46 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 12.9886 - root_mean_squared_error: 3.4430
46/46 ━━━━━━━━━━━━━━━━━━━━ 7s 64ms/step - loss: 5.3780 - root_mean_squared_error: 2.3191 - val_loss: 1.2320 - val_root_mean_squared_error: 1.1100

Epoch 2/3

 1/46 ━━━━━━━━━━━━━━━━━━━━ 7s 160ms/step - loss: 0.8726 - root_mean_squared_error: 0.9342
 8/46 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9246 - root_mean_squared_error: 0.9614
12/46 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.9321 - root_mean_squared_error: 0.9653
19/46 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9400 - root_mean_squared_error: 0.9695
26/46 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9434 - root_mean_squared_error: 0.9712
34/46 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9437 - root_mean_squared_error: 0.9714
43/46 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9440 - root_mean_squared_error: 0.9715
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.9422 - root_mean_squared_error: 0.9706 - val_loss: 0.8502 - val_root_mean_squared_error: 0.9221

Epoch 3/3

 1/46 ━━━━━━━━━━━━━━━━━━━━ 15s 347ms/step - loss: 0.6900 - root_mean_squared_error: 0.8307
 5/46 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6775 - root_mean_squared_error: 0.8229
 8/46 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.7047 - root_mean_squared_error: 0.8390
 9/46 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.7108 - root_mean_squared_error: 0.8427
10/46 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.7142 - root_mean_squared_error: 0.8447
12/46 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.7208 - root_mean_squared_error: 0.8486
14/46 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.7254 - root_mean_squared_error: 0.8514
19/46 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.7289 - root_mean_squared_error: 0.8535
26/46 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.7276 - root_mean_squared_error: 0.8528
31/46 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.7291 - root_mean_squared_error: 0.8537
32/46 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.7295 - root_mean_squared_error: 0.8539
34/46 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.7304 - root_mean_squared_error: 0.8545
36/46 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.7312 - root_mean_squared_error: 0.8550
40/46 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.7318 - root_mean_squared_error: 0.8553
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.7251 - root_mean_squared_error: 0.8515 - val_loss: 0.7076 - val_root_mean_squared_error: 0.8412

 1/12 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 0.5608 - root_mean_squared_error: 0.7488
 8/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6604 - root_mean_squared_error: 0.8116
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.7076 - root_mean_squared_error: 0.8412

 25%|██▌       | 1/4 [01:30<03:56, 78.67s/trial, best loss: 0.7447970509529114]

2026/09/07 04:14:10 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run stately-stoat-485 at: http://127.0.0.1:5000/#/experiments/1/runs/6b14162baeaa4062a553fa6535d7b0fe

🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

Epoch 1/3

 1/46 ━━━━━━━━━━━━━━━━━━━━ 1:10 2s/step - loss: 34.1426 - root_mean_squared_error: 5.8432
 8/46 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.2637 - root_mean_squared_error: 4.7708
11/46 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 20.7699 - root_mean_squared_error: 4.4943
14/46 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 18.8311 - root_mean_squared_error: 4.2646
16/46 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 17.7588 - root_mean_squared_error: 4.1318
18/46 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 16.8520 - root_mean_squared_error: 4.0169
21/46 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 15.7092 - root_mean_squared_error: 3.8681
22/46 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 15.3733 - root_mean_squared_error: 3.8233
25/46 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 14.4655 - root_mean_squared_error: 3.6998
26/46 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 14.1912 - root_mean_squared_error: 3.6617
27/46 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 13.9287 - root_mean_squared_error: 3.6248
28/46 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 13.6777 - root_mean_squared_error: 3.5891
29/46 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 13.4371 - root_mean_squared_error: 3.5546
32/46 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 12.7738 - root_mean_squared_error: 3.4578
34/46 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 12.3737 - root_mean_squared_error: 3.3982
39/46 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 11.4924 - root_mean_squared_error: 3.2631
43/46 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 10.8893 - root_mean_squared_error: 3.1678
45/46 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 10.6156 - root_mean_squared_error: 3.1237
46/46 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - loss: 4.6120 - root_mean_squared_error: 2.1476 - val_loss: 0.9395 - val_root_mean_squared_error: 0.9693

Epoch 2/3

 1/46 ━━━━━━━━━━━━━━━━━━━━ 32s 714ms/step - loss: 1.2040 - root_mean_squared_error: 1.0973
11/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8808 - root_mean_squared_error: 0.9369
21/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8374 - root_mean_squared_error: 0.9139
32/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8050 - root_mean_squared_error: 0.8961
43/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7816 - root_mean_squared_error: 0.8829
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.7001 - root_mean_squared_error: 0.8367 - val_loss: 0.6418 - val_root_mean_squared_error: 0.8011

Epoch 3/3

 1/46 ━━━━━━━━━━━━━━━━━━━━ 3s 71ms/step - loss: 0.4378 - root_mean_squared_error: 0.6616
12/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5263 - root_mean_squared_error: 0.7251
22/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5379 - root_mean_squared_error: 0.7332
33/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5501 - root_mean_squared_error: 0.7414
44/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5601 - root_mean_squared_error: 0.7481
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.5944 - root_mean_squared_error: 0.7710 - val_loss: 0.5803 - val_root_mean_squared_error: 0.7617

 1/12 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.4700 - root_mean_squared_error: 0.6856
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5635 - root_mean_squared_error: 0.7500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.5803 - root_mean_squared_error: 0.7617

 50%|█████     | 2/4 [02:09<01:57, 58.66s/trial, best loss: 0.7447970509529114]

2026/09/07 04:14:49 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run magnificent-fawn-897 at: http://127.0.0.1:5000/#/experiments/1/runs/8d3662b53f4740ee8d9ebdead9cf284c

🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

Epoch 1/3

 1/46 ━━━━━━━━━━━━━━━━━━━━ 1:18 2s/step - loss: 29.2208 - root_mean_squared_error: 5.4056
 8/46 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 30.5159 - root_mean_squared_error: 5.5239
13/46 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 30.2308 - root_mean_squared_error: 5.4980
14/46 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 30.1878 - root_mean_squared_error: 5.4941
18/46 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 29.9718 - root_mean_squared_error: 5.4743
23/46 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 29.6569 - root_mean_squared_error: 5.4453
29/46 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 29.2268 - root_mean_squared_error: 5.4052
36/46 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 28.6887 - root_mean_squared_error: 5.3543
42/46 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 28.2020 - root_mean_squared_error: 5.3077
46/46 ━━━━━━━━━━━━━━━━━━━━ 3s 26ms/step - loss: 24.0827 - root_mean_squared_error: 4.9074 - val_loss: 15.8721 - val_root_mean_squared_error: 3.9840

Epoch 2/3

 1/46 ━━━━━━━━━━━━━━━━━━━━ 5s 120ms/step - loss: 15.1244 - root_mean_squared_error: 3.8890
10/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 14.8292 - root_mean_squared_error: 3.8508
19/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 14.5247 - root_mean_squared_error: 3.8107
27/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 14.1284 - root_mean_squared_error: 3.7575
34/46 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 13.7765 - root_mean_squared_error: 3.7095
41/46 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 13.4338 - root_mean_squared_error: 3.6618
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 11.0525 - root_mean_squared_error: 3.3245 - val_loss: 7.2978 - val_root_mean_squared_error: 2.7014

Epoch 3/3

 1/46 ━━━━━━━━━━━━━━━━━━━━ 35s 786ms/step - loss: 6.3970 - root_mean_squared_error: 2.5292
10/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6.8139 - root_mean_squared_error: 2.6100
19/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6.6762 - root_mean_squared_error: 2.5834
31/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4800 - root_mean_squared_error: 2.5448
41/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3114 - root_mean_squared_error: 2.5109
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.4767 - root_mean_squared_error: 2.3402 - val_loss: 4.1123 - val_root_mean_squared_error: 2.0279

 1/12 ━━━━━━━━━━━━━━━━━━━━ 1s 173ms/step - loss: 4.4585 - root_mean_squared_error: 2.1115
 6/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.2430 - root_mean_squared_error: 2.0596
11/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.1778 - root_mean_squared_error: 2.0438
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 4.1123 - root_mean_squared_error: 2.0279

 75%|███████▌  | 3/4 [02:45<00:48, 48.45s/trial, best loss: 0.7447970509529114]

2026/09/07 04:15:26 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run flawless-crane-834 at: http://127.0.0.1:5000/#/experiments/1/runs/3e786766737142e2b7f8c63050def71c

🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

100%|██████████| 4/4 [03:13<00:00, 48.35s/trial, best loss: 0.7447970509529114]

2026/09/07 04:15:53 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Best parameters: {'lr': np.float64(0.03639081856402229), 'momentum': np.float64(0.2021902157185983)}
Best eval rmse: 0.7447970509529114
🏃 View run casual-hog-592 at: http://127.0.0.1:5000/#/experiments/1/runs/027ba5d011e24b1fa4df129c41d5ac08
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

In [45]:
# Load model as a PyFuncModel.
model_uri = 'models:/m-1c10f04e5d4e45f9bc47d3c1bcd3e7ab/'
loaded_model = mlflow.pyfunc.load_model(model_uri)

# Predict on a Pandas DataFrame.
import pandas as pd
loaded_model.predict(pd.DataFrame(test_x))

Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 47.51it/s]

39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

array([[6.2615747],
       [6.6557026],
       [6.3611484],
       ...,
       [6.048317 ],
       [6.560148 ],
       [5.6048846]], shape=(1225, 1), dtype=float32)